{
  "agc": 1,
  "notes": "An 840K disk INIT'd by the DOS that boots examples/TESTKOM9_840.agc, under this emulator: the VTOC, the empty catalog and the two sectors the free map continues into, exactly as its 6502 code wrote them. Every other track is zeroed — the system it wrote to tracks 0-7 is not ours to carry, and nothing here reads it. What the disk says about those tracks stays in the map.",
  "machine": {
    "model": 7,
    "ram": 64
  },
  "media": [
    {
      "name": "init840.dsk",
      "gz": [
        "H4sIAAAAAAAAA+3Yu02DQRCF0bUx7+cYUw99kZmchAr+BgiogwZogcyhIxYROELCCGFdDOdII20w",
        "Wn3acFsDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgO+b1Hintdf57cX8fhiG4eVp8fB4",
        "92HtZnWYjlobrtpo3b29L9fOu+sv7G1yWu38+JtulZqsTtPZ+Hn4zDhbuhm1my7Iqr10QVbtpwuy",
        "6iBdkFWH6YKsOkoXZNVxuiCrTtIFWXWaLsiqs3RBVp2nC7LqIl2QVZUuyKppuiCrLtMFWTVLF5BU",
        "a7/yAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAt",
        "0fui9b78twMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPBb",
        "9b5ovS+3bgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAA+FveALzJ2cYAIA0A"
      ]
    }
  ]
}
