#!/usr/bin/env python3
"""Generate roms/roms.js from an Agat Emulator data tree.

  python3 tools/build_roms.py [--data DIR] [--check]

DIR defaults to a checkout/extraction of the agat-emulator data package, i.e. a
directory containing roms/, fnts/, palette/. As a fallback each blob can also be
taken from an AgatF distribution directory (--agatf), because the two projects
ship byte-identical ROMs — see ROMS.md.

Everything lands in one <script> as gzip+base64 so the page runs from file://
with no build step and no fetch. Total is around 11 KB.
"""
import argparse
import base64
import gzip
import hashlib
import os
import sys

# key -> (agat-emulator relative path, AgatF filename, expected size)
BLOBS = {
    'monitor7': ('roms/monitor7.rom',   'agatF-sysmon7.bin',    2048),
    'monitor9': ('roms/monitor9.rom',   'agatF-sysmon9.bin',    2048),
    'teac':     ('roms/teac.rom',       'agatF-fd800.bin',       256),
    'shugart7': ('roms/shugart7.rom',   'agatF-fd140-105.bin',   256),
    'shugart9': ('roms/shugart9.rom',   'agatF-fd140-173.bin',   256),
    'font7':    ('fnts/agathe7.fnt',    'agatF-font7-g-32.bin', 2048),
    'font9':    ('fnts/agathe9.fnt',    'agatF-font9-32.bin',   2048),
}

PALETTE = ('palette/16colorshigh.pal', 'agatF-pal16.txt')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def find(data, agatf, rel, alt):
    if data:
        p = os.path.join(data, rel)
        if os.path.exists(p):
            return p
    if agatf:
        p = os.path.join(agatf, alt)
        if os.path.exists(p):
            return p
    return None


def read_palette(path):
    """A .pal is plain text: 16 lines of decimal 'R G B'."""
    out = []
    with open(path) as fh:
        for line in fh:
            parts = line.split()
            if len(parts) >= 3:
                out.append([int(x) for x in parts[:3]])
            if len(out) == 16:
                break
    if len(out) != 16:
        raise SystemExit('%s: expected 16 colours, got %d' % (path, len(out)))
    return out


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument('--data', default=os.environ.get('AGAT_DATA'),
                    help='agat-emulator data dir containing roms/ fnts/ palette/')
    ap.add_argument('--agatf', default='/home/am/src/agat/AgatF-emulator',
                    help='AgatF distribution dir (fallback source)')
    ap.add_argument('--check', action='store_true',
                    help='only report what would be used, with hashes')
    args = ap.parse_args(argv)

    found, rows = {}, []
    for key, (rel, alt, size) in BLOBS.items():
        path = find(args.data, args.agatf, rel, alt)
        if not path:
            raise SystemExit('cannot find %s (looked for %s / %s)' % (key, rel, alt))
        blob = open(path, 'rb').read()
        if len(blob) != size:
            raise SystemExit('%s: expected %d bytes, got %d' % (path, size, len(blob)))
        found[key] = blob
        rows.append((key, path, len(blob), hashlib.md5(blob).hexdigest()))

    pal_path = find(args.data, args.agatf, PALETTE[0], PALETTE[1])
    if not pal_path:
        raise SystemExit('cannot find a palette file')
    palette = read_palette(pal_path)
    rows.append(('palette', pal_path, os.path.getsize(pal_path),
                 hashlib.md5(open(pal_path, 'rb').read()).hexdigest()))

    for key, path, size, md5 in rows:
        print('%-10s %6d  %s  %s' % (key, size, md5, path))
    if args.check:
        return

    out = os.path.join(ROOT, 'roms', 'roms.js')
    with open(out, 'w') as fh:
        fh.write('// Generated by tools/build_roms.py -- do not edit.\n')
        fh.write('// Provenance and licensing: see ROMS.md\n')
        fh.write('window.AGAT_ROMS = {\n')
        for key in sorted(found):
            b64 = base64.b64encode(gzip.compress(found[key], 9)).decode('ascii')
            fh.write('  %s: "%s",\n' % (key, b64))
        fh.write('  palette: %s,\n' % (palette,))
        fh.write('};\n')
    print('\nwrote %s (%d bytes)' % (out, os.path.getsize(out)))


if __name__ == '__main__':
    main(sys.argv[1:])
